jobs:
 - template: default.yml@templates
   parameters:
     minrust: 1.37.0 # static-assertions
     codecov_token: $(CODECOV_TOKEN_SECRET)

resources:
  repositories:
    - repository: templates
      type: github
      name: crate-ci/azure-pipelines
      ref: refs/heads/v0.4
      endpoint: jonhoo
