[package]
name = "msql-proto"
version = "0.1.0"
authors = ["Jon Gjengset <jon@thesquareplanet.com>"]

[dependencies]
nom = { version = "4.0.0-alpha1", features = ["nightly"] }
mysql_common = "0.4"
byteorder = "1"

[dev-dependencies]
mysql = "12.0.4"
