[package]
name = "msql-srv"
version = "0.5.1"

description = "Vindings for emulating a MySQL/MariaDB server"
readme = "README.md"

authors = ["Jon Gjengset <jon@thesquareplanet.com>"]

documentation = "https://docs.rs/msql-srv"
homepage = "https://github.com/jonhoo/msql-srv"
repository = "https://github.com/jonhoo/msql-srv.git"

keywords = ["api-bindings", "database", "sql", "mock"]
categories = ["api-bindings", "network-programming", "database-implementations"]

license = "MIT/Apache-2.0"

[badges]
travis-ci = { repository = "jonhoo/msql-srv" }
appveyor = { repository = "jonhoo/msql-srv", branch = "master", service = "github" }
codecov = { repository = "jonhoo/msql-srv", branch = "master", service = "github" }

[dependencies]
nom = "4.0.0-alpha1"
mysql_common = "0.4"
byteorder = "1"
chrono = "0.4"

[dev-dependencies]
postgres = "0.15"
mysql = "12.0.4"
slab = "0.4"
